import logging
from google.api_core import exceptions

from app.core.clients import run_query
from app.services.sql_service import generate_sql
from app.services.calc_service import calculate_metrics

logger = logging.getLogger(__name__)


def ask_question(question: str, org_id: int, data_type_id: int, reported_data_end: str):
    max_retries = 2
    last_error = None
    
    for attempt in range(max_retries + 1):
        # On the first attempt, last_error is None. On retries, we pass the error back to the LLM.
        logger.info(f"Generating SQL (Attempt {attempt + 1}/{max_retries + 1})")
        sql_response = generate_sql(question, org_id, data_type_id, reported_data_end, error_message=last_error)
        
        numerator_sql = sql_response.numerator_query
        denominator_sql = sql_response.denominator_query
        
        if not numerator_sql:
            logger.error("No SQL generated by the LLM.")
            return {"error": "No SQL generated"}
            
        try:
            # Running the numerator query
            logger.info("Executing numerator query.")
            numerator_result = run_query(numerator_sql)
            
            # Running the denominator query if it exists
            denominator_result = None
            if denominator_sql:
                logger.info("Executing denominator query.")
                denominator_result = run_query(denominator_sql)

            # Calculate the final metrics 
            logger.info("Calculating final metrics.")
            calculated_results = calculate_metrics(
                query_type=sql_response.query_type,
                numerator_data=numerator_result,
                denominator_data=denominator_result
            )

            # Returning the results
            return {
                "numerator_sql": numerator_sql,
                "denominator_sql": denominator_sql,
                "numerator_data": numerator_result,
                "denominator_data": denominator_result,
                "calculated_results": calculated_results 
            }
            
        except exceptions.BadRequest as e:
            last_error = str(e)
            
            # Check for missing column error 
            if "Not found: Column" in last_error or "column not found" in last_error.lower():
                logger.error(f"Missing column detected: {last_error}")
                return {
                    "error": "Missing Column",
                    "details": f"The database is missing a required column. Error: {last_error}"
                }
            
            # Check for syntax error and retry
            logger.warning(f"BigQuery execution failed on attempt {attempt + 1}: {last_error}")
            continue

    # Return error if max retries reached
    logger.error("Max retries reached. Could not fix the SQL query.")
    return {
        "error": "Max retries reached",
        "details": last_error,
        "message": "Tried to fix the SQL query but kept getting errors."
    }
